name: hugo publish

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: YabZhang/yabzhang.github.io
        publish_branch: main
        publish_dir: ./public
        user_name: yabzhang
        user_email: yabzhang2015@gmail.com
