name: hugo publish

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update theme
      run: git submodule update --init --recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3'
        extended: true

    - name: Build
      run: hugo  --enableGitInfo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: YabZhang/yabzhang.github.io
        publish_branch: main
        publish_dir: ./public
        user_name: yabzhang
        user_email: yabzhang2015@gmail.com
